From 108f0e04ad2ed3dc287f1b71b987a7e9d66072ba Mon Sep 17 00:00:00 2001
From: Nikhil Komawar <nikhil.komawar@rackspace.com>
Date: Wed, 05 Feb 2014 23:39:53 +0000
Subject: Removes logging of location uri

This patch removes logging of sensitive store location uri, which
is logged when an exception occurs while trying to get the object
from the store or due to a failure in getting the store api due to
unauthorized context.

fixes bug 1275062

Change-Id: I679baa0897f242f4b8372c9c1c7ab28ae811f5e5
---
diff --git a/glance/store/__init__.py b/glance/store/__init__.py
index b16fc5b..fa80b15 100644
--- a/glance/store/__init__.py
+++ b/glance/store/__init__.py
@@ -658,9 +658,9 @@ class ImageProxy(glance.domain.proxy.Image):
 
                 return data
             except Exception as e:
-                LOG.warn(_('Get image %(id)s data from %(loc)s '
-                           'failed: %(err)s.') % {'id': self.image.image_id,
-                                                  'loc': loc, 'err': e})
+                LOG.warn(_('Get image %(id)s data failed: '
+                           '%(err)s.') % {'id': self.image.image_id,
+                                          'err': e})
                 err = e
         # tried all locations
         LOG.error(_('Glance tried all locations to get data for image %s '
--
cgit v0.9.2
