# https://bugzilla.gnome.org/show_bug.cgi?id=569214
# https://bugzilla.redhat.com/show_bug.cgi?id=481556
# https://bugs.gentoo.org/show_bug.cgi?id=257004
--- a/gedit/gedit-python-module.c	2009-03-16 22:18:36.000000000 +0100
+++ b/gedit/gedit-python-module.c	2009-03-16 22:18:48.000000000 +0100
@@ -398,7 +398,7 @@
 	PyObject *gettext, *install, *gettext_args;
 	struct sigaction old_sigint;
 	gint res;
-	char *argv[] = { "gedit", NULL };
+	char *argv[] = { GEDIT_PLUGINS_LIBS_DIR, NULL };
 	
 	static gboolean init_failed = FALSE;
 
--- a/gedit/Makefile.am	2009-03-16 22:18:55.000000000 +0100
+++ b/gedit/Makefile.am	2009-03-16 22:19:29.000000000 +0100
@@ -24,6 +24,7 @@
 	$(NO_STRICT_ALIASING_CFLAGS)	\
 	$(PYGTK_CFLAGS)			\
 	$(PYTHON_CFLAGS)		\
+	-DGEDIT_PLUGINS_LIBS_DIR=\"$(libdir)/gedit-2/plugins\"          \
 	$(AM_CFLAGS)
 endif
 
